# this example fly.toml file configures flyctl for an app

app = "lingering-cloud-1737"

[build]
  builder = "github.com/superfly/builders//static"

[[services]]
  protocol = "TCP"
  internal_port = 8080
  [port.80]
    handlers = ["HTTP"]
  [port.443]
    handlers = ["TLS","HTTP"]