# this example fly.toml file configures flyctl for an app

app = "damp-fire-3810"

[build]
  builder = "github.com/superfly/builders//static"

[[services]]
  protocol = "TCP"
  internal_port = 8080
  concurrency = "50,70"
  [services.port.80]
    handlers = ["HTTP"]
  [services.port.443]
    handlers = ["TLS","HTTP"]
  [[services.http_check]]
    interval = "10s"
    name = "check-0b904b65497f"
    timeout = "2s"
    method = "get"
    path = "/"
  [[services.tcp_check]]
    interval = "10s"
    name = "check-acc6f00a5300"
    timeout = "2s"