before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
  ignore:
  - goos: darwin
    goarch: 386
  ldflags:
    - -X github.com/superfly/flyctl/flyctl.BuildDate={{.Date}} 
    - -X github.com/superfly/flyctl/flyctl.Version={{ .Version }}
    - -X github.com/superfly/flyctl/flyctl.Commit={{ .ShortCommit }}
archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files: [only-the-binary*]
  wrap_in_directory: false
  format: tar.gz
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    github:
      owner: superfly
      name: homebrew-tap
    folder: Formula
    homepage: https://fly.io
    test: |
      system "#{bin}/flyctl version"
# snapcrafts:
#   -
#     id: flyctl
#     name: flyctl
#     # publish: true
#     summary: Command line tools for the Fly.io platform.
#     description: Fly’s global application platform runs your backend apps all over the world, auto scales based on actual load, and balances capacity to get your users the lowest latency possible.
#     grade: stable
#     confinement: strict
#     license: Apache-2.0
#     apps:
#       flyctl:
#         plugs: ["home", "network", "fly-config", "docker"]
#     plugs:
#       fly-config:
#         interface: personal-files
#         write:
#         - $HOME/.fly