[flyctl]
usage="flyctl"
shortHelp="The Fly CLI"
longHelp="""flyctl is a command line interface to the Fly.io platform.

It allows users to manage authentication, application creation, deployment, network configuration, logging and more
with just the one command.
"""


[info]
usage="info"
shortHelp="Show detailed App information"
longHelp="""Shows information about the application on the Fly platform

Information includes the application's
* name, owner, version, status and hostname
* services
* IP addresses
"""


[apps]
usage="apps"
shortHelp="Manage Apps"
longHelp="""The **apps** commands focus on managing your Fly applications.
Start with the **create** command to register your application.
The **list** command will list all currently registered applications.
"""
[apps.list]
usage="list"
shortHelp="List applications"
longHelp="""The **apps list** command will show the applications currently registered and available to this user. The list will include applications from all the organizations the user is a member of. Each application will be shown with its name, owner and when it was last deployed.
"""
[apps.create]
usage="create [APPNAME]"
shortHelp="Create a new application"
longHelp="""The **apps create** command will both register a new application with the Fly platform and create the fly.toml file which controls how the application will be deployed. The **--builder** flag allows a cloud native buildpack to be specified which will be used instead of a Dockerfile to create the application image when it is deployed.
"""
[apps.destroy]
usage="destroy [APPNAME]"
shortHelp="Permanently destroys an App"
longHelp="""The **apps destroy** command will remove an application from the Fly platform.
"""
[apps.move]
usage="move [APPNAME]"
shortHelp="Move an App to another organization"
longHelp="""The **apps move** command will move an application to another organization the current user belongs to.
"""



[auth]
usage="auth"
shortHelp="Manage authentication"
longHelp="""Authenticate with Fly (and logout if you need to).
If you do not have an account, start with the **auth signup** command.
If you do have and account, begin with the **auth login** subcommand.
"""
[auth.whoami]
usage="whoami"
shortHelp="Show the currently authenticated user"
longHelp="""Displays the users email address/service identity currently authenticated and in use.
"""
[auth.token]
usage="token"
shortHelp="Show the current auth token"
longHelp="""Shows the authentication token that is currently in use. This can be used as an authentication token with API services, independent of flyctl.
"""
[auth.login]
usage="login"
shortHelp="Log in a user"
longHelp="""Logs a user into the Fly platform. Supports browser-based, email/password and one-time-password
authentication. Defaults to using browser-based authentication.
"""
[auth.logout]
usage="logout"
shortHelp="Logs out the currently logged in user"
longHelp="""Log the currently logged-in user out of the Fly platform. To continue interacting with Fly, the user will need to log in again.
"""
[auth.signup]
usage="signup"
shortHelp="Create a new fly account"
longHelp="""Creates a new fly account. The command opens the browser and sends the user to a form to provide appropriate credentials.
"""

[builds]
usage="builds"
shortHelp="Work with Fly Builds"
longHelp="""Fly Builds are templates to make developing Fly applications easier.
"""
[builds.list]
usage="list"
shortHelp="List builds"
longHelp="""
"""
[builds.logs]
usage="logs"
shortHelp="Show logs associated with builds"
longHelp="""
"""


[certs]
usage="certs"
shortHelp="Manage certificates"
longHelp="""Manages the certificates associated with a deployed application. Certificates are created by associating a hostname/domain with the application. When Fly is then able to validate that hostname/domain, the platform gets certificates issued for the hostname/domain by Let's Encrypt.
"""
[certs.list]
usage="list"
shortHelp="List certificates for an App."
longHelp="""List the certificates associated with a deployed application.
"""
[certs.create]
usage="create <hostname>"
shortHelp="Create a certificate for an App."
longHelp="""Creates a certificate for an application. Takes a hostname as a parameter for the certificate.
"""
[certs.delete]
usage="delete <hostname>"
shortHelp="Delete certificate"
longHelp="""Deletes a certificate from an application. Takes hostname as a parameter to locate the certificate.
"""
[certs.show]
usage="show <hostname>"
shortHelp="Shows detailed certificate information"
longHelp="""Shows detailed certificate information for an application. Takes hostname as a parameter to locate the
certificate.
"""
[certs.check]
usage="check <hostname>"
shortHelp="Checks DNS configuration"
longHelp="""Checks the DNS configuration for the specified hostname. Displays results in the same format as the **show** command.
"""

[curl]
usage="curl <url>"
shortHelp="Run a performance test against a url"
longHelp="""Run a performance test againt a url.
"""


[config]
usage="config"
shortHelp="Manage an Apps configuration"
longHelp="""The **config** commands allow you to work with an application's configuration.
"""
[config.display]
usage="display"
shortHelp="Display an App's configuration"
longHelp="""Display an application's configuration. The configuration is presented as in JSON format. The configuration data is retrieved from the Fly service.
"""
[config.save]
usage="save"
shortHelp="Save an App's config file"
longHelp="""Save an application's configuration locally. The configuration data is retrieved from the Fly service and saved in TOML format.
"""
[config.validate]
usage="validate"
shortHelp="Validate an App's config file"
longHelp="""Validates an application's config file against the Fly platform to ensure it is correct and meaningful to the platform. 
"""


[deploy]
usage="deploy"
shortHelp="Deploy an App to the Fly platform"
longHelp="""Deploy an application to the Fly platform. The application can be a local image, remote image, defined in a Dockerfile or use a CNB Buildpack.

Use the --image/-i flag to specify a local or remote image to deploy.

Use the --detach flag to return immediately from starting the deployment rather than monitoring the deployment progress.
"""

[docs]
usage="docs"
shortHelp="View Fly documentation"
longHelp="""View Fly documentation on the Fly.io website. This command will open a browser to view the content.
"""

[history]
usage="history"
shortHelp="List an App's change history"
longHelp="""List the history of changes in the application. Includes autoscaling events and their results.
"""

[ips]
usage="ips"
shortHelp="Manage IP addresses for Apps"
longHelp="""The **ips** commands manage IP addresses for applications. An application can have a number of IP addresses associated with it and this family of commands allows you to list, allocate and release those addresses. It supports both IPv4 and IPv6 addresses.
"""
[ips.list]
usage="list"
shortHelp="List allocated IP addresses"
longHelp="""Lists the IP addresses allocated to the application.
"""
[ips.allocate-v4]
usage="allocate-v4"
shortHelp="Allocate an IPv4 address"
longHelp="""Allocates an IPv4 address to the application.
"""
[ips.allocate-v6]
usage="allocate-v6"
shortHelp="Allocate an IPv6 address"
longHelp="""Allocates an IPv6 address to the application.
"""
[ips.release]
usage="release [ADDRESS]"
shortHelp="Release an IP address"
longHelp="""Releases an IP address from the application.
"""

[logs]
usage="logs"
shortHelp="View App logs"
longHelp="""View application logs as generated by the application running on the Fly platform.

Logs can be filtered to a specific instance using the --instance/-i flag or to all instances running in a specific
region using the --region/-r flag.
"""

[platform]
usage="platform"
shortHelp="Fly platform information"
longHelp="""The **platform** commands are for users looking for information about the fly.io platform.
"""

[platform.regions]
usage="regions"
shortHelp="List regions"
longHelp="""View a list of regions where Fly has edges and/or datacenters
"""

[platform.vmsizes]
usage="vm-sizes"
shortHelp="List VM Sizes"
longHelp="""View a list of VM sizes which can be used with the **flyctl scale vm** command
"""

[releases]
usage="releases"
shortHelp="List App releases"
longHelp="""List all the releases of the application onto the Fly platform, including type, when, success/fail and
which user triggered the release.
"""

[scale]
usage="scale"
shortHelp="Scale App resources"
longHelp="""Scale application resources
"""

[scale.regions]
usage="regions [flags] REGION=COUNT REGION=COUNT ..."
shortHelp="Configure region placement for an App"
longHelp="""Configure the region placement rules and instance count for an application. Shows the current autoscaling configuration if no arguments are given.
"""

[scale.vm]
usage="vm [flags] [SIZE]"
shortHelp="Scale the VM size for an App."
longHelp="""Change the size of the VM to the named size for an application. Shows the application's current VM size if no arguments are given. 

Supported sizes and their names are shown with the command **flyctl platform vm-sizes**.
"""

[secrets]
usage="secrets"
shortHelp="Manage App secrets"
longHelp="""Manage application secrets with the set and unset commands.

Secrets are provided to applications at runtime as ENV variables. Names are
case sensitive and stored as-is, so ensure names are appropriate for
the application and vm environment.
"""
[secrets.list]
usage="list"
shortHelp="Lists the secrets available to the App"
longHelp="""List the secrets available to the application. It shows each secret's name, a digest of the its value and the time the secret was last set. The actual value of the secret is only available to the application.
"""
[secrets.set]
usage="set [flags] NAME=VALUE NAME=VALUE ..."
shortHelp="Set one or more encrypted secrets for an App"
longHelp="""Set one or more encrypted secrets for an application.

Secrets are provided to application at runtime as ENV variables. Names are
case sensitive and stored as-is, so ensure names are appropriate for
the application and vm environment.

Any value that equals "-" will be assigned from STDIN instead of args.
"""
[secrets.unset]
usage="unset [flags] NAME NAME ..."
shortHelp="Remove encrypted secrets from an App"
longHelp="""Remove encrypted secrets from the application. Unsetting a secret removes its availability to
the application.
"""

[status]
usage="status"
shortHelp="Show App status"
longHelp="""Show the application's current status including application details, tasks, most recent deployment details
and in which regions it is currently allocated.
"""

[version]
usage="version"
shortHelp="Show version information for the flyctl command"
longHelp="""Shows version information for the flyctl command itself, including version number and build date.
"""

