name: Homebrew Bump Formula
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "flyctl release version"

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: flyctl
          tag-name: ${{ github.event.inputs.version }}
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
