name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: pre-commit/action@v3.0.0
      - uses: golangci/golangci-lint-action@v3
      - run: go mod download
