on:
  push:
    tags:
      - "v*"
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Release
        uses: docker://goreleaser/goreleaser
        env:
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        with:
          args: release
